import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { LXGW_WenKai_TC } from "next/font/google"; // Chinese font, used as a fallback for Lubrifont SC-like style

import "./globals.css";
import { Header } from "@/src/components/layout/Header";

// Load the fonts
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-primary",
  display: "swap",
});

const lubrifont = LXGW_WenKai_TC({
  subsets: ["latin"],
  variable: "--font-secondary",
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${lubrifont.variable} scroll-smooth`}>
      <body>
        <Header />
        <main className="pt-20">
          {children}
        </main>
      </body>
    </html>
  );
}
